
instaspots_spots_webservice:
    path:     /webservice
    defaults: { _controller: InstaspotsSpotsBundle:Webservice:webservice }

instaspots_spots_home:
    path:     /
    defaults: { _controller: InstaspotsSpotsBundle:News:index }

instaspots_spots_news:
    path:     /
    defaults: { _controller: InstaspotsSpotsBundle:News:news }

instaspots_spots_download:
    path:     /download
    defaults: { _controller: InstaspotsSpotsBundle:News:download }

instaspots_spots_view:
    path:     /advert/{id}
    defaults: { _controller: InstaspotsSpotsBundle:News:view }

instaspots_spots_add:
    path:     /add
    defaults: { _controller: InstaspotsSpotsBundle:News:add }
