
instaspots_spots_home:
    path:     /
    defaults: { _controller: InstaspotsSpotsBundle:Advert:index }

instaspots_spots_view:
    path:     /advert/{id}
    defaults: { _controller: InstaspotsSpotsBundle:Advert:view }

instaspots_spots_add:
    path:     /add
    defaults: { _controller: InstaspotsSpotsBundle:Advert:add }
