version: '3.7'

services:
  web:
    build: ./DjangoProject
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./DjangoProject/:/usr/src/app/
    ports:
      - 2711:8000
    #env_file:
    #- ./.env.dev
  db:
    image: postgis:13-master
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
