version: '3.7'

services:
  web:
    build:
      context: ./DjangoProject
      dockerfile: Dockerfile.prod
    command: gunicorn lowerspot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /mnt/sdb/opt/lowerspot/volumes/static_volume:/home/app/web/static
      - /mnt/sdb/opt/lowerspot/volumes/media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./env.prod
    depends_on:
      - db
  db:
    image: postgis/postgis:13-master
    volumes:
      - /mnt/sdb/opt/lowerspot/volumes/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
  nginx:
    build: ./NginxDocker
    volumes:
      - /mnt/sdb/opt/lowerspot/volumes/static_volume:/home/app/web/static
      - /mnt/sdb/opt/lowerspot/volumes/media_volume:/home/app/web/media
    ports:
      - 2811:80
    depends_on:
      - web

