version: '3.7'

services:
  web:
    build: ./DjangoProject
    command: gunicorn lowerspot.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 2811:8000
    env_file:
      - ./env.prod
    depends_on:
      - db
  db:
    image: postgis/postgis:13-master
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
