<?php

namespace Instaspots\SpotsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends EntityRepository
{

  public function getPicturesByNewest()
  {
    $qb = $this->createQueryBuilder('p');

    $qb->orderBy('p.created', 'DESC');

    $qb->setMaxResults(20);

    return $qb->getQuery()
                ->getResult();
  }

}


